-- GENERATED by npm run db:schema. Edit ordered migrations, then regenerate.
-- Supabase SQL Editor bootstrap/upgrade; each migration is transactional. No data is deleted.

-- Migration: 20260930000100_existing_spots.sql
-- Baseline of the existing ITISpot schema. Preserves existing rows.
begin;

-- Run in the Supabase SQL Editor. All data access goes through authenticated server routes.
create table if not exists public.spots (
  id uuid primary key default gen_random_uuid(),
  text text not null check (char_length(btrim(text)) between 1 and 500),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  image_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);
create index if not exists spots_created_idx on public.spots(created_at desc);
alter table public.spots enable row level security;
revoke all on public.spots from anon, authenticated;
grant all on public.spots to service_role;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('spot-images','spot-images',false,10485760,array['image/webp'])
on conflict(id) do update set public=false,file_size_limit=10485760,allowed_mime_types=array['image/webp'];
-- Do not add public SELECT or upload policies for this bucket.

create table if not exists public.rate_limits (
  key text primary key,
  count integer not null,
  reset_at timestamptz not null
);
alter table public.rate_limits enable row level security;
revoke all on public.rate_limits from anon, authenticated;
grant all on public.rate_limits to service_role;
create or replace function public.consume_rate_limit(p_key text,p_limit integer,p_window_seconds integer)
returns boolean language plpgsql security definer set search_path=public as $$
declare current_count integer;
begin
  if p_limit<1 or p_limit>100 or p_window_seconds<1 or p_window_seconds>86400 or length(p_key)>200 then raise exception 'Invalid rate limit parameters'; end if;
  insert into public.rate_limits(key,count,reset_at) values(p_key,1,now()+make_interval(secs=>p_window_seconds))
  on conflict(key) do update set
    count=case when rate_limits.reset_at<=now() then 1 else least(rate_limits.count+1,p_limit+1) end,
    reset_at=case when rate_limits.reset_at<=now() then now()+make_interval(secs=>p_window_seconds) else rate_limits.reset_at end
  returning count into current_count;
  return current_count<=p_limit;
end;
$$;
revoke all on function public.consume_rate_limit(text,integer,integer) from public,anon,authenticated;
grant execute on function public.consume_rate_limit(text,integer,integer) to service_role;

-- Reapplying this file preserves all existing Spots.
create index if not exists rate_limits_reset_idx on public.rate_limits(reset_at);
create or replace function public.force_pending_spot()
returns trigger language plpgsql set search_path=public as $$
begin new.status='pending'; new.archived_at=null; return new; end;
$$;
create or replace trigger spots_insert_pending before insert on public.spots
for each row execute function public.force_pending_spot();
revoke all on function public.force_pending_spot() from public,anon,authenticated;

-- Schedule once daily in Supabase Cron. Hashes are not needed after the window ends.
-- delete from public.rate_limits where reset_at < now();

-- One bounded page plus global counters; search is a literal string, never SQL/filter syntax.
create or replace function public.list_spots_page(p_filter text default 'all',p_search text default '',p_offset integer default 0,p_limit integer default 24)
returns jsonb language plpgsql stable security invoker set search_path=public as $$
declare result jsonb;
begin
  if p_filter is null or p_filter not in ('all','pending','approved','rejected','archived') or p_search is null or length(p_search)>500 or p_offset is null or p_offset<0 or p_offset>2400000 or p_limit is null or p_limit<1 or p_limit>100 then raise exception 'Invalid pagination'; end if;
  with filtered as (
    select * from public.spots where
    (case when p_filter='archived' then archived_at is not null else archived_at is null and (p_filter='all' or status=p_filter) end)
    and position(lower(p_search) in lower(text || ' ' || id::text))>0
  ), page as (select * from filtered order by created_at desc,id desc limit p_limit offset p_offset)
  select jsonb_build_object(
    'spots',coalesce((select jsonb_agg(to_jsonb(page) order by created_at desc,id desc) from page),'[]'::jsonb),
    'total',(select count(*) from filtered),
    'counts',(select jsonb_build_object(
      'all',count(*) filter(where archived_at is null),
      'pending',count(*) filter(where archived_at is null and status='pending'),
      'approved',count(*) filter(where archived_at is null and status='approved'),
      'rejected',count(*) filter(where archived_at is null and status='rejected'),
      'archived',count(*) filter(where archived_at is not null)) from public.spots)
  ) into result;
  return result;
end;
$$;
revoke all on function public.list_spots_page(text,text,integer,integer) from public,anon,authenticated;
grant execute on function public.list_spots_page(text,text,integer,integer) to service_role;
create index if not exists spots_queue_idx on public.spots(status,created_at desc,id desc) where archived_at is null;

commit;

-- Migration: 20260930000200_review_metadata.sql
-- Add moderation metadata without changing the existing states or publishing data.
begin;

alter table public.spots add column if not exists reviewed_at timestamptz;
alter table public.spots add column if not exists rejection_reason text;

-- Historical reviews did not record their own timestamp. Preserve the last known
-- update as an approximation; do not change created_at or any Spot text/status.
update public.spots set reviewed_at = updated_at
where status in ('approved', 'rejected') and reviewed_at is null;

alter table public.spots drop constraint if exists itispot_review_state;
alter table public.spots add constraint itispot_review_state check (
  (status = 'pending' and reviewed_at is null) or
  (status in ('approved', 'rejected') and reviewed_at is not null)
);
alter table public.spots drop constraint if exists itispot_rejection_reason;
alter table public.spots add constraint itispot_rejection_reason check (
  rejection_reason is null or
  (status = 'rejected' and char_length(btrim(rejection_reason)) between 1 and 500)
);
-- Only server-generated UUID names, never an original filename or arbitrary URL.
-- If pre-existing rows violate this constraint, the migration rolls back intact.
alter table public.spots drop constraint if exists itispot_image_path;
alter table public.spots add constraint itispot_image_path check (
  image_path is null or image_path = id::text || '.webp'
);

create or replace function public.force_pending_spot()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.status = 'pending';
  new.archived_at = null;
  new.reviewed_at = null;
  new.rejection_reason = null;
  return new;
end;
$$;
create or replace function public.track_spot_review()
returns trigger language plpgsql set search_path = '' as $$
begin
  if new.id is distinct from old.id or new.created_at is distinct from old.created_at then
    raise exception 'Spot identity and creation time are immutable';
  end if;
  new.updated_at = statement_timestamp();
  if new.status = 'pending' then
    new.reviewed_at = null;
  elsif new.status is distinct from old.status or new.reviewed_at is null then
    new.reviewed_at = statement_timestamp();
  end if;
  if new.status <> 'rejected' then new.rejection_reason = null; end if;
  return new;
end;
$$;
create or replace trigger spots_track_review before update on public.spots
for each row execute function public.track_spot_review();
revoke all on function public.force_pending_spot() from public, anon, authenticated;
revoke all on function public.track_spot_review() from public, anon, authenticated;

create index if not exists spots_page_idx on public.spots(created_at desc, id desc);
comment on column public.spots.reviewed_at is
  'Last moderation time; historical rows use their last known updated_at.';
comment on column public.spots.rejection_reason is
  'Optional private reason (1-500 characters), only for rejected Spots. The current UI does not collect it.';
comment on column public.spots.image_path is
  'Private spot-images object name: Spot UUID plus .webp. Never a public URL.';

commit;

-- Migration: 20260930000300_private_access.sql
-- Backend-mediated architecture: browser roles have no direct data access.
-- Auth + ADMIN_USER_IDS are checked by every admin server route BEFORE service-role I/O.
begin;

alter table public.spots enable row level security;
alter table public.spots force row level security;
alter table public.rate_limits enable row level security;
alter table public.rate_limits force row level security;
revoke all on public.spots, public.rate_limits from public, anon, authenticated, service_role;
grant select, insert, update, delete on public.spots, public.rate_limits to service_role;

-- Restrictive policies also protect against accidentally restored client grants
-- or permissive policies. They do not restrict service_role, which bypasses RLS.
drop policy if exists itispot_no_direct_spots on public.spots;
create policy itispot_no_direct_spots on public.spots as restrictive
for all to anon, authenticated using (false) with check (false);
drop policy if exists itispot_no_direct_rate_limits on public.rate_limits;
create policy itispot_no_direct_rate_limits on public.rate_limits as restrictive
for all to anon, authenticated using (false) with check (false);

-- Supabase owns these tables and already enables RLS. Do not alter their owner
-- or revoke permissions globally: other buckets must retain their own policies.
do $$
begin
  if not exists (select 1 from pg_class where oid = 'storage.objects'::regclass and relrowsecurity)
     or not exists (select 1 from pg_class where oid = 'storage.buckets'::regclass and relrowsecurity) then
    raise exception 'Storage RLS must be enabled by Supabase before applying this migration';
  end if;
end;
$$;
drop policy if exists itispot_private_objects on storage.objects;
create policy itispot_private_objects on storage.objects as restrictive
for all to anon, authenticated
using (bucket_id <> 'spot-images') with check (bucket_id <> 'spot-images');
drop policy if exists itispot_private_bucket on storage.buckets;
create policy itispot_private_bucket on storage.buckets as restrictive
for all to anon, authenticated
using (id <> 'spot-images') with check (id <> 'spot-images');

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('spot-images', 'spot-images', false, 10485760, array['image/webp'])
on conflict(id) do update set public = false,
  file_size_limit = 10485760, allowed_mime_types = array['image/webp'];

-- No SECURITY DEFINER escalation is needed: only the backend may call this RPC.
create or replace function public.consume_rate_limit(p_key text, p_limit integer, p_window_seconds integer)
returns boolean language plpgsql security invoker set search_path = '' as $$
declare current_count integer;
begin
  if p_key is null or char_length(p_key) not between 1 and 200
     or p_limit is null or p_limit not between 1 and 100
     or p_window_seconds is null or p_window_seconds not between 1 and 86400 then
    raise exception 'Invalid rate limit parameters';
  end if;
  insert into public.rate_limits(key, count, reset_at)
  values (p_key, 1, now() + make_interval(secs => p_window_seconds))
  on conflict(key) do update set
    count = case when rate_limits.reset_at <= now() then 1 else least(rate_limits.count + 1, p_limit + 1) end,
    reset_at = case when rate_limits.reset_at <= now() then now() + make_interval(secs => p_window_seconds) else rate_limits.reset_at end
  returning count into current_count;
  return current_count <= p_limit;
end;
$$;
alter function public.list_spots_page(text, text, integer, integer) set search_path = '';
revoke all on function public.consume_rate_limit(text, integer, integer) from public, anon, authenticated;
revoke all on function public.list_spots_page(text, text, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_rate_limit(text, integer, integer) to service_role;
grant execute on function public.list_spots_page(text, text, integer, integer) to service_role;

-- Refresh the Data API schema cache after adding columns/functions.
notify pgrst, 'reload schema';
commit;

-- Migration: 20261004000100_accounts_profiles.sql
-- Optional accounts. This migration never alters spots, admin roles or Storage.
-- Apply only after reviewing ACCOUNTS.md. Existing Auth users get an anonymous
-- generated username, using their actual Auth creation date (no launch-date reset).
begin;

create or replace function public.itispot_valid_username(value text)
returns boolean language sql immutable strict set search_path = '' as $$
  select value ~ '^[A-Za-z0-9._]{3,20}$'
    and regexp_replace(lower(value), '[0-9]', '', 'g') !~ '(^|[._])(admin|administrator|moderator|mod|itispot|official|support|system|root)([._]|$)'
    and regexp_replace(lower(value), '[._0-9]', '', 'g') <> all(array['admin','administrator','moderator','mod','itispot','official','support','system','root'])
    and regexp_replace(translate(lower(value),'013457','oieast'), '[._0-9]', '', 'g') <> all(array['admin','administrator','moderator','mod','itispot','official','support','system','root']);
$$;
revoke all on function public.itispot_valid_username(text) from public;
grant execute on function public.itispot_valid_username(text) to anon, authenticated, service_role;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null constraint profiles_username_valid check(public.itispot_valid_username(username)),
  avatar_key text default null constraint profiles_avatar_placeholder check(avatar_key is null),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists profiles_username_ci on public.profiles(lower(username));
alter table public.profiles enable row level security;
alter table public.profiles force row level security;
revoke all on public.profiles from public, anon, authenticated;
grant select(username, avatar_key) on public.profiles to anon;
grant select on public.profiles to authenticated;
grant update(username) on public.profiles to authenticated;
grant select, insert, update, delete on public.profiles to service_role;

drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select to anon, authenticated using(true);
drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles for update to authenticated
  using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
drop policy if exists profiles_update_guard on public.profiles;
create policy profiles_update_guard on public.profiles as restrictive for update to anon, authenticated
  using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
drop policy if exists profiles_no_insert on public.profiles;
create policy profiles_no_insert on public.profiles as restrictive for insert to anon, authenticated with check(false);
drop policy if exists profiles_no_delete on public.profiles;
create policy profiles_no_delete on public.profiles as restrictive for delete to anon, authenticated using(false);

create or replace function public.itispot_profile_update()
returns trigger language plpgsql set search_path = '' as $$
begin
  if new.id is distinct from old.id or new.created_at is distinct from old.created_at
     or new.avatar_key is distinct from old.avatar_key then
    raise exception 'Immutable profile field' using errcode='42501';
  end if;
  new.username := lower(new.username);
  new.updated_at := clock_timestamp();
  return new;
end;
$$;
revoke all on function public.itispot_profile_update() from public, anon, authenticated;
drop trigger if exists itispot_profile_update on public.profiles;
create trigger itispot_profile_update before update on public.profiles for each row execute function public.itispot_profile_update();

create or replace function public.itispot_create_profile()
returns trigger language plpgsql security definer set search_path = '' as $$
declare chosen text;
begin
  -- Client metadata supplies only the username. No role or privilege is copied.
  chosen := lower(new.raw_user_meta_data ->> 'username');
  if chosen is null or not public.itispot_valid_username(chosen) then
    raise exception 'Invalid profile username' using errcode='23514';
  end if;
  insert into public.profiles(id,username,created_at,updated_at)
    values(new.id,chosen,new.created_at,new.created_at);
  return new;
end;
$$;
revoke all on function public.itispot_create_profile() from public, anon, authenticated;
drop trigger if exists itispot_auth_user_profile on auth.users;
create trigger itispot_auth_user_profile after insert on auth.users for each row execute function public.itispot_create_profile();

insert into public.profiles(id,username,created_at,updated_at)
  select u.id, 'user_' || left(replace(u.id::text,'-',''),15), u.created_at, u.created_at
  from auth.users u where not exists(select 1 from public.profiles p where p.id=u.id)
  on conflict(id) do nothing;
commit;

-- Migration: 20261005000100_comments.sql
-- Comments V1. Spots never acquire an author/account field.
-- Public projection is provided by RPC; only service_role can moderate.
begin;
create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  spot_id uuid not null references public.spots(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 500 and content ~ '[^[:space:]]'),
  status text not null default 'visible' check (status in ('visible','hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.comment_reports (
  id uuid primary key default gen_random_uuid(),
  comment_id uuid not null references public.comments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (char_length(reason) between 3 and 300 and reason ~ '[^[:space:]]'),
  created_at timestamptz not null default now(),
  unique(comment_id,user_id)
);
create index if not exists comments_spot_visible on public.comments(spot_id,created_at desc,id desc) where status='visible';
create index if not exists comments_author on public.comments(user_id);
create index if not exists comment_reports_user on public.comment_reports(user_id);
create index if not exists comment_reports_recent on public.comment_reports(created_at desc);
alter table public.comments enable row level security;
alter table public.comment_reports enable row level security;
revoke all on public.comments, public.comment_reports from public, anon, authenticated;
grant select(id,spot_id,content,created_at,updated_at) on public.comments to anon, authenticated;
grant all on public.comments, public.comment_reports to service_role;

create or replace function public.comment_spot_visible(p_spot uuid) returns boolean
language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.spots where id=p_spot and status='approved' and archived_at is null)
$$;
drop policy if exists comments_public on public.comments;
create policy comments_public on public.comments for select to anon,authenticated
 using(status='visible' and public.comment_spot_visible(spot_id));
drop policy if exists comments_visibility_guard on public.comments;
create policy comments_visibility_guard on public.comments as restrictive for select to anon,authenticated
 using(status='visible' and public.comment_spot_visible(spot_id));
-- No direct client writes, even if a permissive policy is accidentally added.
do $$ declare tab text; op text; begin
 foreach tab in array array['comments','comment_reports'] loop
   foreach op in array array['insert','update','delete'] loop
     execute format('drop policy if exists %I on public.%I',tab||'_'||op||'_guard',tab);
     execute format('create policy %I on public.%I as restrictive for %s to anon,authenticated %s',
       tab||'_'||op||'_guard',tab,op,
       case when op='insert' then 'with check(false)' when op='delete' then 'using(false)' else 'using(false) with check(false)' end);
   end loop;
 end loop;
end $$;
drop policy if exists reports_private on public.comment_reports;
create policy reports_private on public.comment_reports as restrictive for select to anon,authenticated using(false);

create or replace function public.list_comments(p_spot uuid,p_offset integer default 0) returns jsonb
language plpgsql stable security definer set search_path='' as $$
declare result jsonb; begin
 if p_offset is null or p_offset<0 or p_offset>100000 then raise exception 'Invalid page' using errcode='22023'; end if;
 if not public.comment_spot_visible(p_spot) then raise exception 'Spot unavailable' using errcode='P0002'; end if;
 select jsonb_build_object('total',(select count(*) from public.comments where spot_id=p_spot and status='visible'),
   'comments',coalesce(jsonb_agg(row_data order by created_at desc,id desc),'[]'::jsonb)) into result
 from (select c.id,c.created_at,jsonb_build_object('id',c.id,'content',c.content,'created_at',c.created_at,
   'username',p.username,'avatar_key',p.avatar_key,'own',coalesce(c.user_id=auth.uid(),false)) row_data
   from public.comments c join public.profiles p on p.id=c.user_id
   where c.spot_id=p_spot and c.status='visible' order by c.created_at desc,c.id desc limit 20 offset p_offset) rows;
 return result;
end $$;
create or replace function public.comment_counts(p_spots uuid[]) returns jsonb
language plpgsql stable security definer set search_path='' as $$ begin
 if p_spots is null or cardinality(p_spots)>24 then raise exception 'Invalid batch' using errcode='22023'; end if;
 return (select coalesce(jsonb_object_agg(s.id,(select count(*) from public.comments c where c.spot_id=s.id and c.status='visible')),'{}'::jsonb)
   from public.spots s where s.id=any(p_spots) and s.status='approved' and s.archived_at is null);
end $$;
create or replace function public.create_comment(p_spot uuid,p_content text) returns uuid
language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); new_id uuid; normalized text:=regexp_replace(p_content,'^[[:space:]]+|[[:space:]]+$','','g'); begin
 if actor is null then raise exception 'Login required' using errcode='42501'; end if;
 if normalized is null or char_length(normalized) not between 1 and 500 then raise exception 'Invalid comment' using errcode='22023'; end if;
 -- Lock the Spot during the insert: concurrent archive/delete cannot publish a comment on a hidden Spot.
 perform 1 from public.spots where id=p_spot and status='approved' and archived_at is null for share;
 if not found then raise exception 'Spot unavailable' using errcode='P0002'; end if;
 if not public.consume_rate_limit('comment-create:'||actor::text,5,60) then raise exception 'Too many comments' using errcode='P0429'; end if;
 insert into public.comments(spot_id,user_id,content) values(p_spot,actor,normalized) returning id into new_id;
 return new_id;
end $$;
create or replace function public.delete_own_comment(p_comment uuid) returns boolean
language plpgsql security definer set search_path='' as $$ begin
 if auth.uid() is null then raise exception 'Login required' using errcode='42501'; end if;
 delete from public.comments where id=p_comment and user_id=auth.uid();
 return found;
end $$;
create or replace function public.report_comment(p_comment uuid,p_reason text) returns boolean
language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); normalized text:=regexp_replace(p_reason,'^[[:space:]]+|[[:space:]]+$','','g'); begin
 if actor is null then raise exception 'Login required' using errcode='42501'; end if;
 if normalized is null or char_length(normalized) not between 3 and 300 then raise exception 'Invalid reason' using errcode='22023'; end if;
 perform 1 from public.comments where id=p_comment and status='visible' and public.comment_spot_visible(spot_id) for share;
 if not found then raise exception 'Comment unavailable' using errcode='P0002'; end if;
 if exists(select 1 from public.comment_reports where comment_id=p_comment and user_id=actor) then return false; end if;
 if not public.consume_rate_limit('comment-report:'||actor::text,5,600) then raise exception 'Too many reports' using errcode='P0429'; end if;
 insert into public.comment_reports(comment_id,user_id,reason) values(p_comment,actor,normalized) on conflict(comment_id,user_id) do nothing;
 return found;
end $$;
create or replace function public.admin_comments_page(p_filter text default 'reported',p_offset integer default 0) returns jsonb
language plpgsql stable security definer set search_path='' as $$ begin
 if p_filter is null or p_filter not in ('reported','hidden','all') or p_offset is null or p_offset<0 or p_offset>100000 then raise exception 'Invalid filter' using errcode='22023'; end if;
 return (with filtered as (
   select c.*,p.username,p.avatar_key from public.comments c join public.profiles p on p.id=c.user_id
   where p_filter='all' or (p_filter='hidden' and c.status='hidden') or (p_filter='reported' and exists(select 1 from public.comment_reports r where r.comment_id=c.id))
 ), page as (select * from filtered order by created_at desc,id desc limit 20 offset p_offset)
 select jsonb_build_object('total',(select count(*) from filtered),'comments',coalesce((select jsonb_agg(jsonb_build_object(
   'id',c.id,'spot_id',c.spot_id,'content',c.content,'status',c.status,'username',c.username,'avatar_key',c.avatar_key,'created_at',c.created_at,
   'reports',coalesce((select jsonb_agg(jsonb_build_object('reason',r.reason,'created_at',r.created_at) order by r.created_at desc) from
      (select reason,created_at from public.comment_reports where comment_id=c.id order by created_at desc limit 20) r),'[]'::jsonb),
   'report_count',(select count(*) from public.comment_reports where comment_id=c.id)) order by c.created_at desc,c.id desc) from page c),'[]'::jsonb)));
end $$;
create or replace function public.moderate_comment(p_comment uuid,p_action text) returns boolean
language plpgsql security definer set search_path='' as $$ begin
 if p_action='delete' then delete from public.comments where id=p_comment;
 elsif p_action in ('hide','restore') then update public.comments set status=case when p_action='hide' then 'hidden' else 'visible' end, updated_at=now() where id=p_comment;
 else raise exception 'Invalid action' using errcode='22023'; end if;
 return found;
end $$;
revoke all on function public.comment_spot_visible(uuid),public.list_comments(uuid,integer),public.comment_counts(uuid[]),public.create_comment(uuid,text),public.delete_own_comment(uuid),public.report_comment(uuid,text),public.admin_comments_page(text,integer),public.moderate_comment(uuid,text) from public,anon,authenticated;
grant execute on function public.comment_spot_visible(uuid),public.list_comments(uuid,integer),public.comment_counts(uuid[]) to anon,authenticated,service_role;
grant execute on function public.create_comment(uuid,text),public.delete_own_comment(uuid),public.report_comment(uuid,text) to authenticated;
grant execute on function public.admin_comments_page(text,integer),public.moderate_comment(uuid,text) to service_role;
commit;
