-- GENERATED by npm run db:schema. Edit ordered migrations, then regenerate.
-- Supabase SQL Editor bootstrap/upgrade; each migration is transactional. No data is deleted.

-- Migration: 20260930000100_existing_spots.sql
-- Baseline of the existing ITISpot schema. Preserves existing rows.
begin;

-- Run in the Supabase SQL Editor. All data access goes through authenticated server routes.
create table if not exists public.spots (
  id uuid primary key default gen_random_uuid(),
  text text not null check (char_length(btrim(text)) between 1 and 500),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  image_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);
create index if not exists spots_created_idx on public.spots(created_at desc);
alter table public.spots enable row level security;
revoke all on public.spots from anon, authenticated;
grant all on public.spots to service_role;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('spot-images','spot-images',false,10485760,array['image/webp'])
on conflict(id) do update set public=false,file_size_limit=10485760,allowed_mime_types=array['image/webp'];
-- Do not add public SELECT or upload policies for this bucket.

create table if not exists public.rate_limits (
  key text primary key,
  count integer not null,
  reset_at timestamptz not null
);
alter table public.rate_limits enable row level security;
revoke all on public.rate_limits from anon, authenticated;
grant all on public.rate_limits to service_role;
create or replace function public.consume_rate_limit(p_key text,p_limit integer,p_window_seconds integer)
returns boolean language plpgsql security definer set search_path=public as $$
declare current_count integer;
begin
  if p_limit<1 or p_limit>100 or p_window_seconds<1 or p_window_seconds>86400 or length(p_key)>200 then raise exception 'Invalid rate limit parameters'; end if;
  insert into public.rate_limits(key,count,reset_at) values(p_key,1,now()+make_interval(secs=>p_window_seconds))
  on conflict(key) do update set
    count=case when rate_limits.reset_at<=now() then 1 else least(rate_limits.count+1,p_limit+1) end,
    reset_at=case when rate_limits.reset_at<=now() then now()+make_interval(secs=>p_window_seconds) else rate_limits.reset_at end
  returning count into current_count;
  return current_count<=p_limit;
end;
$$;
revoke all on function public.consume_rate_limit(text,integer,integer) from public,anon,authenticated;
grant execute on function public.consume_rate_limit(text,integer,integer) to service_role;

-- Reapplying this file preserves all existing Spots.
create index if not exists rate_limits_reset_idx on public.rate_limits(reset_at);
create or replace function public.force_pending_spot()
returns trigger language plpgsql set search_path=public as $$
begin new.status='pending'; new.archived_at=null; return new; end;
$$;
create or replace trigger spots_insert_pending before insert on public.spots
for each row execute function public.force_pending_spot();
revoke all on function public.force_pending_spot() from public,anon,authenticated;

-- Schedule once daily in Supabase Cron. Hashes are not needed after the window ends.
-- delete from public.rate_limits where reset_at < now();

-- One bounded page plus global counters; search is a literal string, never SQL/filter syntax.
create or replace function public.list_spots_page(p_filter text default 'all',p_search text default '',p_offset integer default 0,p_limit integer default 24)
returns jsonb language plpgsql stable security invoker set search_path=public as $$
declare result jsonb;
begin
  if p_filter is null or p_filter not in ('all','pending','approved','rejected','archived') or p_search is null or length(p_search)>500 or p_offset is null or p_offset<0 or p_offset>2400000 or p_limit is null or p_limit<1 or p_limit>100 then raise exception 'Invalid pagination'; end if;
  with filtered as (
    select * from public.spots where
    (case when p_filter='archived' then archived_at is not null else archived_at is null and (p_filter='all' or status=p_filter) end)
    and position(lower(p_search) in lower(text || ' ' || id::text))>0
  ), page as (select * from filtered order by created_at desc,id desc limit p_limit offset p_offset)
  select jsonb_build_object(
    'spots',coalesce((select jsonb_agg(to_jsonb(page) order by created_at desc,id desc) from page),'[]'::jsonb),
    'total',(select count(*) from filtered),
    'counts',(select jsonb_build_object(
      'all',count(*) filter(where archived_at is null),
      'pending',count(*) filter(where archived_at is null and status='pending'),
      'approved',count(*) filter(where archived_at is null and status='approved'),
      'rejected',count(*) filter(where archived_at is null and status='rejected'),
      'archived',count(*) filter(where archived_at is not null)) from public.spots)
  ) into result;
  return result;
end;
$$;
revoke all on function public.list_spots_page(text,text,integer,integer) from public,anon,authenticated;
grant execute on function public.list_spots_page(text,text,integer,integer) to service_role;
create index if not exists spots_queue_idx on public.spots(status,created_at desc,id desc) where archived_at is null;

commit;

-- Migration: 20260930000200_review_metadata.sql
-- Add moderation metadata without changing the existing states or publishing data.
begin;

alter table public.spots add column if not exists reviewed_at timestamptz;
alter table public.spots add column if not exists rejection_reason text;

-- Historical reviews did not record their own timestamp. Preserve the last known
-- update as an approximation; do not change created_at or any Spot text/status.
update public.spots set reviewed_at = updated_at
where status in ('approved', 'rejected') and reviewed_at is null;

alter table public.spots drop constraint if exists itispot_review_state;
alter table public.spots add constraint itispot_review_state check (
  (status = 'pending' and reviewed_at is null) or
  (status in ('approved', 'rejected') and reviewed_at is not null)
);
alter table public.spots drop constraint if exists itispot_rejection_reason;
alter table public.spots add constraint itispot_rejection_reason check (
  rejection_reason is null or
  (status = 'rejected' and char_length(btrim(rejection_reason)) between 1 and 500)
);
-- Only server-generated UUID names, never an original filename or arbitrary URL.
-- If pre-existing rows violate this constraint, the migration rolls back intact.
alter table public.spots drop constraint if exists itispot_image_path;
alter table public.spots add constraint itispot_image_path check (
  image_path is null or image_path = id::text || '.webp'
);

create or replace function public.force_pending_spot()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.status = 'pending';
  new.archived_at = null;
  new.reviewed_at = null;
  new.rejection_reason = null;
  return new;
end;
$$;
create or replace function public.track_spot_review()
returns trigger language plpgsql set search_path = '' as $$
begin
  if new.id is distinct from old.id or new.created_at is distinct from old.created_at then
    raise exception 'Spot identity and creation time are immutable';
  end if;
  new.updated_at = statement_timestamp();
  if new.status = 'pending' then
    new.reviewed_at = null;
  elsif new.status is distinct from old.status or new.reviewed_at is null then
    new.reviewed_at = statement_timestamp();
  end if;
  if new.status <> 'rejected' then new.rejection_reason = null; end if;
  return new;
end;
$$;
create or replace trigger spots_track_review before update on public.spots
for each row execute function public.track_spot_review();
revoke all on function public.force_pending_spot() from public, anon, authenticated;
revoke all on function public.track_spot_review() from public, anon, authenticated;

create index if not exists spots_page_idx on public.spots(created_at desc, id desc);
comment on column public.spots.reviewed_at is
  'Last moderation time; historical rows use their last known updated_at.';
comment on column public.spots.rejection_reason is
  'Optional private reason (1-500 characters), only for rejected Spots. The current UI does not collect it.';
comment on column public.spots.image_path is
  'Private spot-images object name: Spot UUID plus .webp. Never a public URL.';

commit;

-- Migration: 20260930000300_private_access.sql
-- Backend-mediated architecture: browser roles have no direct data access.
-- Auth + ADMIN_USER_IDS are checked by every admin server route BEFORE service-role I/O.
begin;

alter table public.spots enable row level security;
alter table public.spots force row level security;
alter table public.rate_limits enable row level security;
alter table public.rate_limits force row level security;
revoke all on public.spots, public.rate_limits from public, anon, authenticated, service_role;
grant select, insert, update, delete on public.spots, public.rate_limits to service_role;

-- Restrictive policies also protect against accidentally restored client grants
-- or permissive policies. They do not restrict service_role, which bypasses RLS.
drop policy if exists itispot_no_direct_spots on public.spots;
create policy itispot_no_direct_spots on public.spots as restrictive
for all to anon, authenticated using (false) with check (false);
drop policy if exists itispot_no_direct_rate_limits on public.rate_limits;
create policy itispot_no_direct_rate_limits on public.rate_limits as restrictive
for all to anon, authenticated using (false) with check (false);

-- Supabase owns these tables and already enables RLS. Do not alter their owner
-- or revoke permissions globally: other buckets must retain their own policies.
do $$
begin
  if not exists (select 1 from pg_class where oid = 'storage.objects'::regclass and relrowsecurity)
     or not exists (select 1 from pg_class where oid = 'storage.buckets'::regclass and relrowsecurity) then
    raise exception 'Storage RLS must be enabled by Supabase before applying this migration';
  end if;
end;
$$;
drop policy if exists itispot_private_objects on storage.objects;
create policy itispot_private_objects on storage.objects as restrictive
for all to anon, authenticated
using (bucket_id <> 'spot-images') with check (bucket_id <> 'spot-images');
drop policy if exists itispot_private_bucket on storage.buckets;
create policy itispot_private_bucket on storage.buckets as restrictive
for all to anon, authenticated
using (id <> 'spot-images') with check (id <> 'spot-images');

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('spot-images', 'spot-images', false, 10485760, array['image/webp'])
on conflict(id) do update set public = false,
  file_size_limit = 10485760, allowed_mime_types = array['image/webp'];

-- No SECURITY DEFINER escalation is needed: only the backend may call this RPC.
create or replace function public.consume_rate_limit(p_key text, p_limit integer, p_window_seconds integer)
returns boolean language plpgsql security invoker set search_path = '' as $$
declare current_count integer;
begin
  if p_key is null or char_length(p_key) not between 1 and 200
     or p_limit is null or p_limit not between 1 and 100
     or p_window_seconds is null or p_window_seconds not between 1 and 86400 then
    raise exception 'Invalid rate limit parameters';
  end if;
  insert into public.rate_limits(key, count, reset_at)
  values (p_key, 1, now() + make_interval(secs => p_window_seconds))
  on conflict(key) do update set
    count = case when rate_limits.reset_at <= now() then 1 else least(rate_limits.count + 1, p_limit + 1) end,
    reset_at = case when rate_limits.reset_at <= now() then now() + make_interval(secs => p_window_seconds) else rate_limits.reset_at end
  returning count into current_count;
  return current_count <= p_limit;
end;
$$;
alter function public.list_spots_page(text, text, integer, integer) set search_path = '';
revoke all on function public.consume_rate_limit(text, integer, integer) from public, anon, authenticated;
revoke all on function public.list_spots_page(text, text, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_rate_limit(text, integer, integer) to service_role;
grant execute on function public.list_spots_page(text, text, integer, integer) to service_role;

-- Refresh the Data API schema cache after adding columns/functions.
notify pgrst, 'reload schema';
commit;
